"""
Name(s): Ayodeji Syvlain and Christopher Lee
Name of Project: The Adventure of the Brick Prison: Infiltration
Description: A trivia/adventure game with a plot revolving around Hunter College High School.
"""
import time
import os
import random
bossname = "Sami"
def tennis():
  print("             |")
  time.sleep(0.1)
  os.system('clear')
  print("o            |")
  time.sleep(0.05)
  os.system('clear')
  print("=o           |")
  time.sleep(0.05)
  os.system('clear')
  print("==o          |")
  time.sleep(0.05)
  os.system('clear')
  print("-==o         |")  
  time.sleep(0.05)
  os.system('clear')
  print("--==o        |")
  time.sleep(0.05)
  os.system('clear')
  print("---==o       |")
  time.sleep(0.05)
  os.system('clear')
  print("----==o      |")
  time.sleep(0.05)
  os.system('clear')
  print("-----==o     |")
  time.sleep(0.05)
  os.system('clear')
  print("------==o    |")
  time.sleep(0.05)
  os.system('clear')
  print("-------==o   |")
  time.sleep(0.05)
  os.system('clear')
  print(" -------==o  |")
  time.sleep(0.05)
  os.system('clear')
  print("  -------==o |")
  time.sleep(0.05)
  os.system('clear')
  pls = time.time()
  he = input(" -------==o|")
  work = time.time()
  if end - start > 0.2:
    a = 1
    time.sleep(0.05)
    os.system('clear')
    print("  ------o=|")
    time.sleep(0.05)
    os.system('clear')
    print("   ----o==|")
    time.sleep(0.05)
    os.system('clear')
    print("    --o==-|")
    time.sleep(0.05)
    os.system('clear')
    print("     o==--|")
    time.sleep(0.05)
    os.system('clear')
    print("    o==---|")
    time.sleep(0.05)
    os.system('clear')
    print("   o==---|")
    time.sleep(0.05)
    os.system('clear')
    print("  o==----|")
    time.sleep(0.05)
    os.system('clear')
    print(" o==----|")
    time.sleep(0.05)
    os.system('clear')
    print("o==------|")
    time.sleep(0.05)
    os.system('clear')
    print("==------ |")
    time.sleep(0.05)
    os.system('clear')
    print("=------  |")
    time.sleep(0.05)
    os.system('clear')
    print("------   |")
    time.sleep(0.05)
    os.system('clear')
    print("-----    |")
    time.sleep(0.05)
    os.system('clear')
    print("----     |")
    time.sleep(0.05)
    os.system('clear')
    print("---      |")
    time.sleep(0.05)
    os.system('clear')
    print("--       |")
    time.sleep(0.05)
    os.system('clear')
    print("-        |")
    time.sleep(0.05)
    os.system('clear')
  else:
    a = 2
  return a
def checkpoint1():
  os.system('clear')
  print("-> Sami sees you. His systems activate towards any intruders so he starts charging towards you, jacket and all.")
  time.sleep(5)
  os.system('clear')
  print("AUSTIN: Uh oh, he's running straight at us. Do something!")
  time.sleep(3)
  os.system('clear')
  import page1
  time.sleep(1)
  os.system('clear')
  print("S")
  time.sleep(0.5)
  os.system('clear')
  print("SA")
  time.sleep(0.5)
  os.system('clear')
  print("SAM")
  time.sleep(0.5)
  os.system('clear')
  print("SAMI")
  time.sleep(5)
  os.system('clear')
  start = time.time()
  dodgesami = input("-> Sami tries to slam into you. You have 5 seconds to DODGE. Press 'd' to DODGE.")
  end = time.time()
  if end - start > 5:
    print("AUSTIN: You responded too late. Crap, here he comes!")
    time.sleep(2)
    os.system('clear')
    print(user.lower() + "...")
    time.sleep(1.5)
    os.system('clear')
    print(user.title() + "!")
    time.sleep(1)
    os.system('clear')
    print(user.upper() + "!!!")
    time.sleep(1)
    os.system('clear')
    time.sleep(2)
    print("Oh you're done for...")
    time.sleep(1)
    os.system('clear')
    again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
    checkpoint1()
  elif dodgesami == "d":
    print("-> You successfully dodged Sami's attack. Not that it would have done much damage...wait, actually it might just have healed you. Hmm...")
    time.sleep(4)
    print("-> Sami slams into a wall and collapses, weakened.")
    time.sleep(4)
    print("SAMI: Ugh...what is going on...")
    time.sleep(4)
    print("AUSTIN: Here's a debugger. Use this to remove the program in his brain.")
    time.sleep(5)
    obtaindebugger = input("Press ENTER to take the debugger.")
    os.system('clear')
    print("-> You obtained the debugger! Use it after stunning an enemy to remove the harmful program!")
    time.sleep(5)
    os.system('clear')
    def debugsami():
      os.system('clear')
      db = input("Press ENTER to use the debugger.")
      print("-> You use the debugger on " + bossname + ".")
      time.sleep(3)
      print("AUSTIN: Oh, I forgot to say, you have to answer the trivia question it gives you based on the scan of their brain.")
      time.sleep(3)
      start = time.time()
      triv1 = input("DEBUGGER: What is the name of Super Mario's main villain? 5 seconds...")
      end = time.time()
      triv1 = triv1.lower()
      if end - start > 5:
        print("AUSTIN: Sorry, you took too long, next time, try to respond in under 5 seconds... let's try this again now, shall we?")
        time.sleep(4)
        debugsami()
      elif triv1 == "bowser":
        print("Well done!")
        time.sleep(1)
        os.system('clear')
        print("-> Debugger is loading...")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading..")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading...")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading..")
        time.sleep(3.)
        os.system('clear')
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading...")
        os.system('clear')
        attack()
        print("-> You successfully debugged Sami! ")
        time.sleep(3)
        os.system('clear')
        time.sleep(4)
        print("AUSTIN: Awesome! I wonder how Sami is feeling right now. ")
        time.sleep(2)
        os.system('clear')
        print("-> Sami groggily gets up.")
        time.sleep(1)
        print("SAMI: Hey", str(user), "what are you doing here?")
        time.sleep(1)
        print("I feel like I just got hit by a truck. Well, I'm off to my next class, see ya.")
        time.sleep(3)
        os.system('clear')
        print("-> Sami puts on his jacket and leaves. ")
        time.sleep(2)
        os.system('clear')
      
      else:
        a = input("AUSTIN: Oh great! The debugger broke... looks like we're going on a sidequest... Click ENTER to proceed.")
        os.system('clear')
        print("Alright, you're gonna have to code yourself a new debugger...")
        time.sleep(3)
        os.system('clear')
        fix0 = input("Okay... your gonna have to copy the code I tell you. I'm a bit of a fast talker so youll only have 12 seconds to copy 5 words. Remeber, it's case sensitive. You ready? Click ENTER to proceed. ")
        os.system('clear')
        print("Okay, I'm gonna start in 3...")
        time.sleep(1)
        os.system('clear')
        print("Okay, I'm gonna start in 2..")
        time.sleep(1)
        os.system('clear')
        print("Okay, I'm gonna start in 1.")
        time.sleep(1)
        os.system('clear')
        print("Okay, I'm gonna start in 0")
        time.sleep(1)
        os.system('clear')
        start = time.time()
        fix1 = input("function")
        os.system('clear')
        fix2 = input("input")
        os.system('clear')
        fix3 = input("import")
        os.system('clear')
        fix4 = input("system")
        os.system('clear')
        fix5 = input("else")
        os.system('clear')
        end = time.time()
        if end - start > 12:
          L = input("You took too long, what are we gonna do now! Click ENTER to start from your last checkpoint...")
          checkpoint1()
        elif fix1 == "function" and fix2 == "input" and fix3 == "import" and fix4 == "system" and fix5 == "else":
          print("Wow! Nice job, now let's try this again...")
          debugsami()
    debugsami()
  else:
    print("-> You did not dodge in time. Sami slams into you, and it feels unexpectedly painful. Guess underneath all that jacket is some serious weight")
    time.sleep(3.5)
    print("-> Or maybe he's just enhanced due to the code. I don't want to know.")
    time.sleep(2)
    print("-> You go flying into a bunch of lockers. Struggling to get up, the last thing you see is Sami looming over you. Rest in peace.")
    time.sleep(4)
    print("YOU WERE TURNED INTO A ROBOT. Try again.")
def attack():
  print("           ")
  time.sleep(1)
  os.system('clear')
  print(">           ")
  time.sleep(0.1)
  os.system('clear')
  print("=>           ")
  time.sleep(0.1)
  os.system('clear')
  print("==>          ")
  time.sleep(0.1)
  os.system('clear')
  print("===>         ")
  time.sleep(0.1)
  os.system('clear')
  print("-===>        ")
  time.sleep(0.1)
  os.system('clear')
  print(" -===>       ")
  time.sleep(0.1)
  os.system('clear')
  print("  -===>      ")
  time.sleep(0.1)
  os.system('clear')
  print("   -===>     ")
  time.sleep(0.1)
  os.system('clear')
  print("    -===>    ")
  time.sleep(0.1)
  os.system('clear')
  print("     -===>   ")
  time.sleep(0.1)
  os.system('clear')
  print("      -===>  ")
  time.sleep(0.1)
  os.system('clear')
  print("       -===> ")
  time.sleep(0.1)
  os.system('clear')
  print("        -===>")
  time.sleep(0.1)
  os.system('clear')
  print("         -==*")
  time.sleep(0.1)
  os.system('clear')
  print("          -=*")
  time.sleep(0.1)
  os.system('clear')
  print("            B")
  time.sleep(0.1)
  os.system('clear')
  print("           BZ")
  time.sleep(0.1)
  os.system('clear')
  print("          BZZ")
  time.sleep(0.1)
  os.system('clear')
  print("         BZZZZ")
  time.sleep(0.1)
  os.system('clear')
  print("        BZZZZT")
  time.sleep(0.1)
  os.system('clear')
  print("       BZZZZT ")
  time.sleep(0.1)
  os.system('clear')
  print("      BZZZZT  ")
  time.sleep(0.1)
  os.system('clear')
  print("     BZZZZT   ")
  time.sleep(0.1)
  os.system('clear')
  print("    BZZZZT    ")
  time.sleep(0.1)
  os.system('clear')
  print("   BZZZZT     ")
  time.sleep(0.1)
  os.system('clear')
  print("  BZZZZT      ")
  time.sleep(0.1)
  os.system('clear')
  print(" BZZZZT       ")
  time.sleep(0.1)
  os.system('clear')
  print("BZZZZT        ")
  time.sleep(0.1)
  os.system('clear')
  print("ZZZZT         ")
  time.sleep(0.1)
  os.system('clear')
  print("ZZZT          ")
  time.sleep(0.1)
  os.system('clear')
  print("ZZT           ")
  time.sleep(0.1)
  os.system('clear')
  print("ZT            ")
  time.sleep(0.1)
  os.system('clear')
  print("T             ")
  time.sleep(0.1)
  os.system('clear')
  print("              ")
  time.sleep(0.1)
  os.system('clear')

def handball():
  print("          ")
  time.sleep(0.5)
  os.system('clear')
  print("o         ")
  time.sleep(0.1)
  os.system('clear')
  print("-o          ")
  time.sleep(0.07)
  os.system('clear')
  print("--o         ")
  time.sleep(0.07)
  os.system('clear')
  print("---o        ")  
  time.sleep(0.07)
  os.system('clear')
  print("----o       ")
  time.sleep(0.07)
  os.system('clear')
  print("-----o      ")
  time.sleep(0.07)
  os.system('clear')
  print("------o     ")
  time.sleep(0.07)
  os.system('clear')
  print("-------o    ")
  time.sleep(0.07)
  os.system('clear')
  print("--------o   ")
  time.sleep(0.07)
  os.system('clear')
  print("---------o  ")
  time.sleep(0.07)
  os.system('clear')
  print("----------o  ")
  time.sleep(0.07)
  os.system('clear')
  print("-----------o ")
  time.sleep(0.07)
  os.system('clear')
  print("------------o")
  time.sleep(0.07)
  os.system('clear')
  print("-------------")
  time.sleep(0.07)
  os.system('clear')
  print("-------------")
  time.sleep(0.05)
  os.system('clear')
def checkpoint2():
  bossname = "Emmitt"
  os.system('clear')
  import page1
  time.sleep(3)
  os.system('clear')
  print("E")
  time.sleep(0.5)
  os.system('clear')
  print("EM")
  time.sleep(0.5)
  os.system('clear')
  print("EMM")
  time.sleep(0.5)
  os.system('clear')
  print("EMMI")
  time.sleep(0.5)
  os.system('clear')
  print("EMMIT")
  time.sleep(0.5)
  os.system('clear')
  print("EMMITT")
  time.sleep(1)
  os.system('clear')
  print("-> Through his rimmed glasses, Emmitt spies you and attacks with a handball, throwing it at your head at 80 mph with his superstrength. ")
  time.sleep(5)
  os.system('clear')
  handball()
  os.system('clear')
  time.sleep(1)
  start = time.time()
  dodge_emmitt = input("-> You have 3 seconds to DODGE. Press 'd' to DODGE. ")
  end = time.time()
  if end - start > 3:
    print("AUSTIN: NO! GET OUT OF THE WAY!")
    time.sleep(2)
    os.system('clear')
    print(user.lower() + "...")
    time.sleep(1.5)
    os.system('clear')
    print(user.title() + "!")
    time.sleep(1)
    os.system('clear')
    print(user.upper() + "!!!")
    time.sleep(1)
    os.system('clear')
    time.sleep(2)
    print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
    time.sleep(4)
    os.system('clear')
    again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
    checkpoint2()
  elif dodge_emmitt == "d":
    print("-> You jump out of the way and the ball misses you by a whisker. Maddened, Emmitt throws his toad at you. Wait... what?")
    time.sleep(6)
    print("-> The toad smartly hops away from the battlefield??")
    time.sleep(4)
    print("-> Morally drained from the toad's betrayal, Emmitt sits down not knowing what to do. His circuits are overloading. He takes out his phone and scrolls through some weird anime memes. ")
    time.sleep(8)
    print("AUSTIN: Sheeeesh, those are some strange memes. Anyway, it's gonna be harder to debug him since he's not injured or knocked out. Be prepared!")
    time.sleep(10)
    def debugemmitt():
      demmitt = input("Press ENTER to debug Emmitt: ")
      print("-> You use the debugger on " + bossname + ".")
      time.sleep(3)
      print("-> The debugger scans Emmitt's brain. ")
      time.sleep(2)
      print("AUSTIN: Here's the question.")
      time.sleep(3)
      os.system('clear')
      start = time.time()
      triv2 = input("DEBUGGER: What is the anime about ninja Shinobi? 10 seconds... ")
      end = time.time()
      triv2 = triv2.lower()
      if end - start > 10:
        print("AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds... let's try this again now, shall we?")
        debugemmitt()
        time.sleep(4)
      elif triv2 == "naruto":
        time.sleep(2)
        print("Well done!")
        time.sleep(4)
        os.system('clear')
        print("-> Debugger is loading...")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading..")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading...")
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading..")
        time.sleep(3.)
        os.system('clear')
        time.sleep(0.5)
        os.system('clear')
        print("-> Debugger is loading...")
        os.system('clear')
        attack()
        os.system('clear')
        print("AUSTIN: Huh, it hasn't fully debugged him. I guess we need to do one more.")
        time.sleep(3)
        os.system('clear')
        print("AUSTIN: Whoa, this one is tough. Good luck, you have 10 seconds. ")
        def debugemmitt2():
          start = time.time()
          triv3 = input("DEBUGGER: What is Emmitt's last name? ")
          end = time.time()
          triv3 = triv3.lower()
          if end - start > 10:
            print("AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds... let's try this again now, shall we?")
            debugemmitt2()
            time.sleep(4)
          elif triv3 == "wong":
            time.sleep(2)
            print("Well done!")
            time.sleep(4)
            os.system('clear')
            print("-> Debugger is loading...")
            time.sleep(0.5)
            os.system('clear')
            print("-> Debugger is loading..")
            time.sleep(0.5)
            os.system('clear')
            print("-> Debugger is loading...")
            time.sleep(0.5)
            os.system('clear')
            print("-> Debugger is loading..")
            time.sleep(3.)
            os.system('clear')
            time.sleep(0.5)
            os.system('clear')
            print("-> Debugger is loading...")
            os.system('clear')
            attack()
            os.system('clear')
            print("-> You successfully debugged Emmitt! ")
            time.sleep(3)
            os.system('clear')
            time.sleep(4)
            print("AUSTIN: Awesome! I wonder how Emmitt is feeling right now. ")
            time.sleep(2)
            os.system('clear')
            print("-> Emmitt is knocked out. Perhaps you should kindly move him to the side of the hallway? ")
            time.sleep(3)
            os.system('clear')
            print("AUSTIN: Alright, let's keep investigating! ")
          else: 
            print("That's incorrect, try again!")
            time.sleep(2)
            os.system('clear')
            debugemmitt2()
        debugemmitt2()
      else:
        print("That's incorrect, try again!")
        time.sleep(2)
        os.system('clear')
        debugemmitt()
    debugemmitt()
  else:
    print("AUSTIN: NO! GET OUT OF THE WAY!")
    time.sleep(2)
    os.system('clear')
    print(user.lower() + "...")
    time.sleep(1.5)
    os.system('clear')
    print(user.title() + "!")
    time.sleep(1)
    os.system('clear')
    print(user.upper() + "!!!")
    time.sleep(1)
    os.system('clear')
    time.sleep(2)
    print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
    time.sleep(4)
    os.system('clear')
    again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
    checkpoint2()
def checkpoint3b():
  FL = input("AUSTIN: You've got to shut off the faucets, the easiest way to shut one off under water is to push(p) pull(l) twist(t) and hit(h) Okay? Click ENTER to proceed.")
  print("Alright, remember to type each letter that corresponds to the word. This is gonna disappear so take one last look. You will have 7 seconds...")
  time.sleep(8)
  os.system('clear')
  print("3!")
  time.sleep(1)
  os.system('clear')
  print("2!")
  time.sleep(1)
  os.system('clear')
  print("1!")
  time.sleep(1)
  os.system('clear')
  print("GO!")
  time.sleep(1)
  os.system('clear')
  start = time.time()
  sink1 = input("push: ")
  os.system('clear')
  sink2 = input("pull: ")
  os.system('clear')
  sink3 = input("hit: ")
  os.system('clear')
  sink4 = input("push: ")
  os.system('clear')
  sink5 = input("pull: ")
  os.system('clear')
  sink6 = input("twist: ")
  os.system('clear')
  sink7 = input("hit: ")
  os.system('clear')
  end = time.time()
  if end - start > 7:
    print("You took too long.")
    time.sleep(2)
    print("The water rises to the top and you drown.")
    time.sleep(3)
    ag = input("Hit ENTER to try again.")
    os.system('clear')
    checkpoint3b()
  elif sink1 == "p" and sink2 == "l" and sink3 == "h" and sink4 == "p" and sink5 == "l" and sink6 == "t" and sink7 == "h":
    os.system('clear')
    print("AUSTIN: Nice job!")
    time.sleep(1.5)
    os.system('clear')
    print("You have to get close to her and grab her swim goggles, she can't see that way!")
    time.sleep(4)
    os.system('clear')
    print("You will see numbers from 1-10 go by and you must hit ENTER within half a second of it hitting 5 to attack.")
    input("Hit ENTER to proceed")
    rand1 = 0
    while rand1 != 5:
      rand1 = random.randint(1,10)
      print(rand1)
      time.sleep(0.2)
      os.system('clear')
    start = time.time()
    yep = input("5")
    end = time.time()
    if end - start > 0.5:
      print("You took too long... let's try again...")
      time.sleep(3)
      checkpoint3b()
    else:
      print("-> You succesfully grab Lauren's swim goggles. Confused, Lauren stops swmiming, just enough time for you to start up the debugger.")
      time.sleep(4)
      def debuglauren():
        start = time.time()
        triv3b = input("DEBUGGER: What standard swim stroke is named after a flying insect? 10 seconds. ")
        end = time.time()
        triv3b = triv3b.lower()
        if end - start > 10:
          print("AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds... let's try this again now, shall we?")
          debuglauren()
          time.sleep(4)
        elif triv3b == "butterfly":
          time.sleep(2)
          print("Well done!")
          time.sleep(4)
          os.system('clear')
          print("-> Debugger is loading...")
          time.sleep(0.5)
          os.system('clear')
          print("-> Debugger is loading..")
          time.sleep(0.5)
          os.system('clear')
          print("-> Debugger is loading...")
          time.sleep(0.5)
          os.system('clear')
          print("-> Debugger is loading..")
          time.sleep(3.)
          os.system('clear')
          time.sleep(0.5)
          os.system('clear')
          print("-> Debugger is loading...")
          os.system('clear')
          attack()
          os.system('clear')
          print("-> You successfully debugged Lauren! ")
          time.sleep(3)
          os.system('clear')
          time.sleep(2)
          print("-> Lauren opens her eyes. ")
          time.sleep(4)
          print("LAUREN: HI AUSTIN!! :D Oh hey, " + user.title() + "! Why is it flooded in here? Wait...why are you in the girls bathroom...I'm not gonna ask. ")
          time.sleep(7)
          print("-> Lauren walks out of the bathroom. ")
          time.sleep(3)
          os.system('clear')
          
        else:
          print("That's incorrect, try again!")
          time.sleep(2)
          os.system('clear')
          debuglauren()
      debuglauren()
      
  else:
    print("AUSTIN: You messed up! The water is ri-")
    time.sleep(2.6)
    os.system('clear')
    eg = input("The water rises to the top and you drown Click ENTER to try again.")
    os.system('clear')
    checkpoint3b()
def checkpoint3():
  lr = input("Type l to go left, and r to go right. (PLEASE CHOOSE LEFT WE SPENT LOTS OF MORE WORK ON IT unless you wanna fight Jackson)  ")
  lr = lr.lower()
  if lr == "r":
    def checkpoint3a():
      print("Alright off we go to the gym, I guess.")
      time.sleep(4)
      import page7
      print("Alright we're here.")
      time.sleep(2)
      os.system('clear')
      print("-> A basketball comes flying towards your head out of nowhere!")
      time.sleep(3)
      print("JACKSON: Catch!")
      time.sleep(1.4)
      os.system('clear')
      import page1
      time.sleep(1)
      os.system('clear')
      print("J")
      time.sleep(0.5)
      os.system('clear')
      print("JA")
      time.sleep(0.5)
      os.system('clear')
      print("JAC")
      time.sleep(0.5)
      os.system('clear')
      print("JACK")
      time.sleep(0.5)
      os.system('clear')
      print("JACKS")
      time.sleep(0.5)
      os.system('clear')
      print("JACKSO")
      time.sleep(0.5)
      os.system('clear')
      print("JACKSON")
      time.sleep(5)
      os.system('clear')
      start = time.time()
      more = input("Press 'b' to block the basketball. 1 seconds...")
      end = time.time()
      os.system('clear')
      if end - start > 1.1:
        print("You took too long! You get knocked out! YOU ARE TURNED INTO A ROBOT. ")
        time.sleep(3.6)
        agi = ("Press ENTER to try again.")
        os.system('clear')
        checkpoint3a()
      elif more == "b":
        print("AUSTIN: Nice!")
        time.sleep(1.4)
        os.system('clear')
        print("-> The ball glances off your strategically positioned arm and launches itself directly into Jackson's face, knocking him out!")
        time.sleep(4)
        os.system('clear')
        print("AUSTIN: So much for that surprise attack. Lame.")
        time.sleep(3)
        os.system('clear')
        print("AUSTIN: What a silly guy, I don't know if he's even worth debugging, let's move on!")
        time.sleep(4)
        os.system('clear')
      else:
        print("-> The ball ricochets off of you and Austin and you both collapse. That was an epic failure! ")
        time.sleep(4.5)
        jagain = input("YOU ARE TURNED INTO A ROBOT. Press ENTER to try again. ")
        checkpoint3a()
    checkpoint3a()
  if lr == "l":
    print("Okay then, the bathroom it is, I doubt we'll find anything useful...")
    time.sleep(4)
    os.system('clear')
    print("Wait... do you hear that?")
    time.sleep(3)
    os.system('clear')
    time.sleep(1)
    print("Shhh...")
    time.sleep(2)
    os.system('clear')
    print("Is that the sound of...")
    time.sleep(1.5)
    os.system('clear')
    print("Is that the sound of... running water?")
    time.sleep(1.4)
    print("-> You and Austin arrive and enter the bathroom. Water is flooding the floor.")
    time.sleep(3.6)
    print("-> The door slams shut behind you.")
    time.sleep(2)
    os.system('clear')
    print("-> You see a figure in the shadows. ")
    time.sleep(3)
    os.system('clear')
    print("UNKNOWN: Hello, ")
    time.sleep(1)
    os.system('clear')
    print("UNKNOWN: Hello, " + user)
    time.sleep(1)
    os.system('clear')
    print("AUSTIN: Who are you?")
    time.sleep(2)
    os.system('clear')
    print("UNKNOWN: Oh, it doesn't matter... you'll drown in a couple of minutes.")
    time.sleep(3.7)
    os.system('clear')
    print("-> The water begins to rise...")
    time.sleep(2)
    os.system('clear')
    print("AUSTIN: Shoot the water's rising...whoever you are, stop this!")
    time.sleep(2)
    os.system('clear')
    print("UNKNOWN: No I don't think I will.")
    time.sleep(2.5)
    os.system('clear')
    print("-> The figure reveals herself. ")
    time.sleep(2)
    os.system('clear')
    import page1
    time.sleep(3)
    os.system('clear')
    print("L")
    time.sleep(0.5)
    os.system('clear')
    print("LA")
    time.sleep(0.5)
    os.system('clear')
    print("LAU")
    time.sleep(0.5)
    os.system('clear')
    print("LAUR")
    time.sleep(0.5)
    os.system('clear')
    print("LAURE")
    time.sleep(0.5)
    os.system('clear')
    print("LAUREN")
    time.sleep(5)
    os.system('clear')
    print("AUSTIN: Oh no, looks like she's also been programmed to fight us. But, won't she drown?")
    time.sleep(3)
    os.system('clear')
    print("Unless...")
    time.sleep(2)
    os.system('clear')
    print("OH NO! We shouldn't have come here! ")
    time.sleep(2.4)
    os.system('clear')
    print("She's on the swim team! ")
    time.sleep(3)
    os.system('clear')
    print("->The water is up to your NECK already!")
    time.sleep(2.5)
    os.system('clear')
  checkpoint3b()
    
def checkpoint4():
  print("-> The courtyard is empty, except for some of the track kids coming back from practice. ")
  time.sleep(3)
  print("AUSTIN: Quick, hide! If they see us they'll attack and we can't take on that many at once.")
  time.sleep(4)
  os.system('clear')
  hide = input("Press 1 to hide behind the trashcans, press 2 to hide under a bench, press 3 to hide in the handball corner. ")
  if hide == "1" or "2" or "3":
    print("-> You hide from the track kids, and they leave. ")
    time.sleep(6)
    print("AUSTIN: Alright, let's keep investigating. Hold on, who's that? Are they coming back? Quick, hide again!")
    time.sleep(4)
    os.system('clear')
    print("UNKNOWN: Hey Michael, do you want to go to Sing's?")
    time.sleep(5)
    print("MICHAEL: Kayaan, I told you I don't have money on me right now. I'll go with you tomorrow. ")
    time.sleep(5)
    print("KAYAAN: Hey, do you hear something? Yo whoever's hiding there, you're not gonna jumpscare me...")
    time.sleep(4)
    print("-> Kayaan sees you, and in an instant the harmful software in him and Michael start running. ")
    time.sleep(5)
    print("AUSTIN: Darn it, guess we'll have to fight both of them at the same time. This doesn't look good. ")
    time.sleep(4)
    os.system('clear')
    startkmbattle = input("Press ENTER to START BATTLE:")
    os.system('clear')
    time.sleep(1)
    import page1
    time.sleep(1)
    os.system('clear')
    print("K")
    time.sleep(0.5)
    os.system('clear')
    print("KA")
    time.sleep(0.5)
    os.system('clear')
    print("KAY")
    time.sleep(0.5)
    os.system('clear')
    print("KAYA")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAA")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN ")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN A")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AN")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND ")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND M")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MI")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MIC")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MICH")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MICHA")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MICHAE")
    time.sleep(0.5)
    os.system('clear')
    print("KAYAAN AND MICHAEL")
    time.sleep(5)
    os.system('clear')
    def kayaanmichael():
      time.sleep(3)
      print("-> Michael shoots a shotput at blistering speed. You dodge, but he's too quick and slams into you. ")
      time.sleep(4)
      os.system('clear')
      print("-> Michael throws another shotput. ")
      time.sleep(2)
      os.system('clear')
      handball()
      os.system('clear')
      time.sleep(1)
      start = time.time()
      dodge_shotput = input("-> You have 3 seconds to DODGE. Press 'd' to DODGE. ")
      end = time.time()
      if end - start > 3:
        print("AUSTIN: NO! GET OUT OF THE WAY!")
        time.sleep(2)
        os.system('clear')
        print(user.lower() + "...")
        time.sleep(1.5)
        os.system('clear')
        print(user.title() + "!")
        time.sleep(1)
        os.system('clear')
        print(user.upper() + "!!!")
        time.sleep(1)
        os.system('clear')
        time.sleep(2)
        print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
        time.sleep(4)
        os.system('clear')
        again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
        os.system('clear')
        kayaanmichael()
      elif dodge_shotput == "d":
        print("-> Michael throws another shotput, much faster. You'll have to dodge quicker this time. ")
        time.sleep(4)
        os.system('clear')
        handball()
        os.system('clear')
        time.sleep(1)
        start = time.time()
        dodge_shotput = input("-> You have 2 seconds to DODGE. Press 'd' to DODGE. ")
        end = time.time()
        if end - start > 2:
          print("AUSTIN: NO! GET OUT OF THE WAY!")
          time.sleep(2)
          os.system('clear')
          print(user.lower() + "...")
          time.sleep(1.5)
          os.system('clear')
          print(user.title() + "!")
          time.sleep(1)
          os.system('clear')
          print(user.upper() + "!!!")
          time.sleep(1)
          os.system('clear')
          time.sleep(2)
          print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
          time.sleep(4)
          os.system('clear')
          again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
          os.system('clear')
          kayaanmichael()
        elif dodge_shotput == "d":
          os.system('clear')
          print("-> Somehow, you manage to dodge Michael's attack. He rushes towards you for a final attack. Miraculously, he trips on the turf. Kayaan doesn't move a muscle. He seems to be deep in thought. ")
          time.sleep(6)
          os.system('clear')
          def debugmichael():
            print("AUSTIN: Now's your chance! Use the debugger! ")
            pro = input("Press ENTER to use the debugger: ")
            os.system('clear')
            time.sleep(2)
            print("-> The debugger scans Michael's brain. ")
            time.sleep(2)
            os.system('clear')
            start = time.time()
            triv4 = input("DEBUGGER: What is the name of the hit Pokemon mobile game that launched in 2016? Type all lowercase. You have ten seconds. ")
            end = time.time()
            triv4 = triv4.lower()
            if end - start > 10:
              print("AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds... let's try this again now, shall we?")
              time.sleep(4)
              debugmichael()
            elif triv4 == "pokemon go":
              print("Well done!")
              time.sleep(2)
              os.system('clear')
              print("-> Debugger is loading...")
              time.sleep(0.5)
              os.system('clear')
              print("-> Debugger is loading..")
              time.sleep(0.5)
              os.system('clear')
              print("-> Debugger is loading.")
              time.sleep(0.5)
              os.system('clear')
              print("-> Debugger is loading..")
              time.sleep(0.5)
              os.system('clear')
              print("-> Debugger is loading...")
              os.system('clear')
              attack()
              os.system('clear')
              print("-> You succesfully debugged Michael! ")
              time.sleep(2)
              print("AUSTIN: Alright! Now we just have to get Kayaan as well. Wait. What is he doing? ")
              time.sleep(3.5)
              os.system('clear')
              print("KAYAAN: Who closes the bus door once the bus driver gets off? ")
              time.sleep(3)
              print("AUSTIN: What? ")
              time.sleep(1)
              print("KAYAAN: Why is the sky blue? ")
              time.sleep(3)
              print("AUSTIN: Okay, fair enough. ")
              time.sleep(2)
              print("KAYAAN: Does milk spoil inside cows? ")
              time.sleep(3)
              print("AUSTIN: Okay, you've got to stop. ")
              time.sleep(3)
              print("KAYAAN: Do insects pass gas? ")
              time.sleep(3)
              print("AUSTIN: Good question...")
              time.sleep(2)
              print("KAYAAN: Which came first, the chicken or the egg?")
              time.sleep(3)
              print("AUSTIN: (The egg, obviously) Is he okay? Should we try to debug him? ")
              time.sleep(3)
              print("KAYAAN: Do brown cows make chocolate milk? ")
              time.sleep(3)
              print("AUSTIN: What the- Hey", user, "are you okay???")
              time.sleep(3)
              os.system('clear')
              print("-> Kayaan rattles off question after question. Your insides are churning. Your head is spinning. You feel yourself losing consciousness. Austin seems to feel it too after a while. ")
              time.sleep(6)
              print("AUSTIN: Quick, do something! Insult him! Break his concentration! I don't know, say something! ")
              time.sleep(5)
              os.system('clear')
              def insultkayaan():
                insult = input("-> You think of an insult. Enter 1 to call him a track kid (derogatory), enter 2 to call him a BTS lookalike, and enter 3 to comment on his unibrow. ")
                if insult == "1" or insult == "2":
                  os.system('clear')
                  print("It has no effect. Kayaan drones on and on and you and Austin lose consciousness. YOU ARE TURNED INTO A ROBOT. Press ENTER to try again.")
                  insultkayaan()
                elif insult == "3":
                  print("-> You tell Kayaan that his unibrow looks like a cyclops.")
                  time.sleep(3)
                  print("-> Stunned, Kayaan stops talking and sits down, broken. His systems are overloading. Huge emotional damage has been inflicted. You almost want to cry watching him. ")
                  time.sleep(4.8)
                  print("AUSTIN: All right! I couldn't stand hearing that for any longer. You know the drill!")
                  time.sleep(3)
                  os.system('clear')
                  def debugkayaan():
                    kay = input("Press ENTER to debug Kayaan: ")
                    os.system('clear')
                    time.sleep(2)
                    print("-> The debugger scans Kayaan's brain. ")
                    time.sleep(2)
                    os.system('clear')
                    start = time.time()
                    triv5 = input("DEBUGGER: Is water wet? Yes or no? You have 6 seconds. ")
                    end = time.time()
                    if end - start > 6:
                      print("AUSTIN: Sorry, you took too long, next time, try to respond in under 6 seconds... let's try this again now, shall we?")
                      time.sleep(4)
                      debugkayaan()
                    elif triv5 == "yes" or "no":
                      print("Well done! ")
                      time.sleep(2)
                      os.system('clear')
                      print("-> Debugger is loading...")
                      time.sleep(0.5)
                      os.system('clear')
                      print("-> Debugger is loading..")
                      time.sleep(0.5)
                      os.system('clear')
                      print("-> Debugger is loading.")
                      time.sleep(0.5)
                      os.system('clear')
                      print("-> Debugger is loading..")
                      time.sleep(0.5)
                      os.system('clear')
                      print("-> Debugger is loading...")
                      os.system('clear')
                      attack()
                      os.system('clear')
                      print("-> You succesfully debugged Kayaan!")
                      time.sleep(4)
                      os.system('clear')
                      print("-> Kayaan is fast asleep. ")
                      print("AUSTIN: Now that was the weirdest question we've had. Is that all Kayaan thinks about? Let's continue with our journey, shall we? ")
                      time.sleep(4)
                  debugkayaan()
                else:
                  print("That's not an option.")
                  insultkayaan()
              insultkayaan()             
                  
            else:  
              print("That's incorrect, try again!")
              time.sleep(2)
              os.system('clear')
              debugmichael()
          debugmichael()
          
        else:
          print("AUSTIN: NO! GET OUT OF THE WAY!")
          time.sleep(2)
          os.system('clear')
          print(user.lower() + "...")
          time.sleep(1.5)
          os.system('clear')
          print(user.title() + "!")
          time.sleep(1)
          os.system('clear')
          print(user.upper() + "!!!")
          time.sleep(1)
          os.system('clear')
          time.sleep(2)
          print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
          again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
          kayaanmichael()
      else:
        print("AUSTIN: NO! GET OUT OF THE WAY!")
        time.sleep(2)
        os.system('clear')
        print(user.lower() + "...")
        time.sleep(1.5)
        os.system('clear')
        print(user.title() + "!")
        time.sleep(1)
        os.system('clear')
        print(user.upper() + "!!!")
        time.sleep(1)
        os.system('clear')
        time.sleep(2)
        print("AUSTIN: Rest in peace", str(user), "...I'm out of here!!")
        again = input("YOU WERE TURNED INTO A ROBOT. CLICK ENTER TO TRY AGAIN")
        kayaanmichael()
    kayaanmichael()
  else:
    print("That's not a choice, silly.")
    time.sleep(3)
    os.system('clear')
    checkpoint4()

def checkpoint6(): 
  print("MR CHENG: So, it's you who's been debugging everyone. I can't say I expected any less of you, even with the help of genius Austin here, who is now under my control. ")
  time.sleep(6)
  os.system('clear')
  print("YOU: Why are you doing this? What could a class of robots do for you? ")
  time.sleep(4)
  print("MR CHENG: For once, there will be a role model class of students, that get good grades, study hard, and succeed in life! I'm only doing this for the good of 9-3. ")
  time.sleep(6)
  os.system('clear')
  print("I've programmed them so that they have the freedom to choose their own extracurriculars and subject majors, and they will be enhanced to the highest degree.")
  time.sleep(5.5)
  os.system('clear')
  print("I know you've fought against Michael's extreme shotput throwing, Lauren's enhanced underwater breathing, and Jackson's upper body strength.")
  time.sleep(5)
  os.system('clear')
  print("I'm allowing them to find success in what they enjoy most, and yet still be able to find fun in life, as I've kept their personalities and social lives the same. Doesn't that sound like a perfect world to you?")
  time.sleep(7)
  os.system('clear')
  print("There will be no more stressing about grades, practicing sports or committing to extracurriculars every week. ")
  time.sleep(4)
  os.system('clear')
  def join():
    jon = input("-> You think about what he says for a while and find some truth in it. Do you choose to join MR CHENG? Yes or no? Type 'y' or 'n'.")
    jon = jon.lower()
    if jon == "y":
      os.system('clear')
      print("MR CHENG: I knew you'd be reasonable. Put this receptor on your head and it'll all be done in an instant. ")
      time.sleep(4)
      print("-> You put on the headset and in a few seconds you fade into unconsciousness. You are aware of the world around you...")
      time.sleep(5)
      print("-> Time passes. You excel in your grades and get into your first choice college. You also excelin fitness and health, now being jacked without even working out. You grow up, get married, and by age 40 the program wears off and you are completely your own self. But are you really happy with this life that the code has left you with? ")
      time.sleep(17)
      os.system('clear')
      print("PROGRAM: Yes.")
      time.sleep(1)
      os.system('clear')
      print("PROGRAM: Yes. Yes you are.")
      time.sleep(3)
      os.system('clear')
      restart = input("GAME OVER. Press ENTER to restart your life from that one crucial decision. ")
      os.system('clear')
      join()
    elif jon == "n":
      def chengno():  
        print("MR CHENG: No matter. You will join me. ")
        time.sleep(2.2)
        os.system('clear')
        print("You have no say in the matter.")
        time.sleep(4)
        print("-> Mr. Cheng gets behind a massive computer and turns it on. It is much larger than Austin's laptop, and has a weird sort of glow around it. ")
        time.sleep(5)
        os.system('clear')
        print("-> Mr. Cheng is about to release a barrage of attacks, get ready to defend yourself.") 
        time.sleep(3)
        os.system('clear')
        print("You will have to unscramble the code attacks, but all within a time limit of 30 seconds as Mr. Cheng has more WPM. You have 10 seconds to prepare. ")
        time.sleep(10)
        os.system('clear')
        print("3!")
        time.sleep(1)
        os.system('clear')
        print("2!")
        time.sleep(1)
        os.system('clear')
        print("1!")
        time.sleep(1)
        os.system('clear')
        print("GO!")
        time.sleep(1)
        os.system('clear')
        time.sleep(2.6)
        start = time.time()
        cscram1 = input("remoev: ")
        os.system('clear')
        cscram2 = input("anhniiltae: ")
        os.system('clear')
        cscram3 = input("demosilh: ")
        os.system('clear')
        end = time.time()
        if start - end > 30:
          mind = input("Too slow. Your mind is destroyed by Mr Cheng's code. YOU ARE TURNED INTO A ROBOT. Press ENTER to try again. ")
          os.system('clear')
          chengno()
        elif cscram1 == "remove" and cscram2 == "annihilate" and cscram3 == "demolish":
          time.sleep(1)
          def chengp2():
            print("Mr. Cheng: Not bad, not bad! I'm telling you, you'll make a great programmer once you stop resisting. Take this! ")
            time.sleep(5)
            os.system('clear')
            start = time.time()
            cscram4 = input("tesydro: ")
            os.system('clear')
            cscram5 = input("dleete: ")
            os.system('clear')
            cscram6 = input("vapzoire: ")
            os.system('clear')
            end = time.time()
            if start - end > 30:
              mch = input("Too slow. Your mind is destroyed by Mr Cheng's code. YOU ARE TURNED INTO A ROBOT. Press ENTER to try again. ")
              os.system('clear')
              chengp2()
            elif cscram4 == "destroy" and cscram5 == "delete" and cscram6 == "vaporize":
              print("Mr. Cheng: Shoot, my computer isn't loading...")
              time.sleep(4)
              os.system('clear')
              print("-> You get close to Mr. Cheng's computer and quietly sync your debugger with his keyboard. Whatever you type now affects whatis being typed on his computer. Austin really planned ahead with his gadget! You must save Austin and thank him. ")
              time.sleep(5)
              def breakcheng():
                print("-> Mr. Cheng is writing code to fix his computer too fast for you to unscramble. ")
                time.sleep(3)
                os.system('clear')
                chengthing = input("You must break his code by making syntax errors. Press ENTER to continue.")
                os.system('clear')        
                print("When he types a function you must type a counter-fucntion and vice versa. str <-> int. while <-> for. print <-> clear. if <-> else. Press ENTER to continue. ")
                time.sleep(4)
                os.system('clear')
                time.sleep(7)
                print("3!")
                time.sleep(1)
                os.system('clear')
                print("2!!")
                time.sleep(1)
                os.system('clear')
                print("1!!!")
                time.sleep(1)
                os.system('clear')
                print("GO!!!!")
                time.sleep(1)
                os.system('clear')
                brk1 = input("if: ")
                os.system('clear')
                brk2 = input("str: ")
                os.system('clear')
                brk3 = input("print: ")
                os.system('clear')
                brk4 = input("else: ")
                os.system('clear')
                brk5 = input("while: ")
                os.system('clear')
                brk6 = input("print: ")
                os.system('clear')
                brk7 = input("for: ")
                os.system('clear')
                brk8 = input("int: ")
                if brk1 == "else" and brk2 == "int" and brk3 == "input" and brk4 == "if" and brk5 == "for" and brk6 == "input" and brk7 == "while" and brk8 == "str":
                  print("-> Mr. Cheng's computer goes up in flames.")
                  time.sleep(2.6)
                  print("MR CHENG: Shoot...you're quite a talented coder. I shouldn't underestimate you, then. ")
                  time.sleep(3)
                  time.sleep(1.3)
                  os.system('clear')
                  print("YOU: Now bring back Austin and my friends! Your plan isn't going to work in the long run! I know you're a good man inside. ")
                  print("MR CHENG: Please don't do this. ")
                  time.sleep(2)
                  print("YOU: You're not going anywhere. Now decode my friends! ")
                  time.sleep(3)
                  os.system('clear')
                  print("You")
                  time.sleep(0.6)
                  os.system('clear')
                  print("You leave")
                  time.sleep(0.3)
                  os.system('clear')
                  print("You leave me")
                  time.sleep(1)
                  os.system('clear')
                  print("You leave me no")
                  time.sleep(0.2)
                  os.system('clear')
                  print("You leave me no choice.")
                  time.sleep(3)
                  os.system('clear')
                  print("Mr. Cheng summons an ATP Head Wilson Babolat Pure Drive Radical Blade4000 racket, made from graphite infused with enhanced performance chips. ")
                  time.sleep(6)
                  os.system('clear')
                  type = input("-> Mr. Cheng tosses a spiked metal tennis ball and serves it at you at point blank range. You hear a deafening pop and realise that this ball has just broken the sound barrier. press ENTER within 0.2 seconds of it reaching you to deflect this before it blows through you. Hit ENTER to continue.")
                  print("             |")
                  time.sleep(0.1)
                  os.system('clear')
                  print("o            |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("=o           |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("==o          |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("-==o         |")  
                  time.sleep(0.05)
                  os.system('clear')
                  print("--==o        |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("---==o       |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("----==o      |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("-----==o     |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("------==o    |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("-------==o   |")
                  time.sleep(0.05)
                  os.system('clear')
                  print(" -------==o  |")
                  time.sleep(0.05)
                  os.system('clear')
                  print("  -------==o |")
                  time.sleep(0.05)
                  os.system('clear')
                  pls = time.time()
                  he = input(" -------==o|")
                  work = time.time()
                  if work - pls > 0.2:
                    a = 1
                    time.sleep(0.05)
                    os.system('clear')
                    print("  ------o=|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("   ----o==|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("    --o==-|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("     o==--|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("    o==---|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("   o==---|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("  o==----|")
                    time.sleep(0.05)
                    os.system('clear')
                    print(" o==----|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("o==------|")
                    time.sleep(0.05)
                    os.system('clear')
                    print("==------ |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("=------  |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("------   |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("-----    |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("----     |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("---      |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("--       |")
                    time.sleep(0.05)
                    os.system('clear')
                    print("-        |")
                    time.sleep(0.05)
                    os.system('clear')
                  else:
                    a = 2
                  return a
                  if work - pls > 0.2:
                    impale = input("You took too long. The tennis ball impales you and you fall to the floor in agony. YOU DIED. Press ENTER to try again. ")
                    os.system('clear')
                    breakcheng() 
                  else:
                    print("-> You deflect the ball and it collides with Mr. Cheng, knocking him down. ")
                    time.sleep(4)
                    os.system('clear')
                    print("MR CHENG: I won't give up on my goal, no matter what happens. ")
                    time.sleep(3)
                    print("-> Mr. Cheng gets up with renewed energy and limps out of the room. You are too late, and collapse in frustration. Suddenly... ")
                    time.sleep(5)
                    os.system('clear')
                    print("-> Sami, Emmitt, Lauren, Jackson, Kayaan, and Michael enter the room, blocking him. ")
                    time.sleep(3.7)
                    print("-> This is truly the power of friendship! Real, not forged through code!")
                    time.sleep(4)
                    print("YOU: It's over. How could you have thought this was the right thing to do? ")
                    time.sleep(3)
                    print("MR CHENG: It would have worked. It was for the good of 9-3 and for you guys, my students. ")
                    time.sleep(4)
                    print("YOU: This isn't true freedom, even if you code them to be aware and make their own decisions. What if someone doesn't want to excel in something that you code them to excel in? ")
                    time.sleep(6)
                    print("MR CHENG: They still would have achieved greatness. ")
                    time.sleep(2)
                    os.system('clear')
                    print("YOU: That's true. But, think about it. There are no shortcuts in life. ")
                    time.sleep(2)
                    print("MR CHENG: ...")
                    time.sleep(2)
                    print("YOU: Isn't the journey itself sometimes more important than getting to your destination? ")
                    time.sleep(4)
                    print("MR CHENG: ...")
                    time.sleep(3)
                    os.system('clear')
                    print("MR CHENG: *sigh* You're right. This code is wrong. Let's undo everything that's happened. ")
                    time.sleep(4)
                    os.system('clear')
                    print("A few moments later, all of your classmates arrive, fully debugged. You look around, moved by all the smiling faces. Mr. Cheng starts tearing up. ")
                    time.sleep(6.3)
                    os.system('clear')
                    print("->  " + user.title() + "!")
                    time.sleep(1.5)
                    os.system('clear')
                    print("-> Wait who's that?")
                    time.sleep(2)
                    print("AUSTIN: Long time no see, " + user.title() + "!")
                    time.sleep(4)
                    os.system('clear')
                    print("WRITTEN BY AYODEJI SYLVAIN AND CHRISTOPHER LEE")
                    time.sleep(1)
                    print("CREDITS TO AUSTIN Z, SAMI H, EMMITT W, LAUREN N, JACKSON C, KAYAAN M, MICHAEL P, and MR. CHENG to agreeing to be in this adventure. ")
                    time.sleep(5)
                    print("DEDICATED TO AUSTIN ZHAO, CS9 intern, graduating 2022! WE LOVE YOU AUSTIN! <3 You're literally the best intern ever, we will miss you! ")
                    time.sleep(10)
                    os.system('clear')
                    print("Thanks for playing, we'll see you next time! - Chris and Deji ")
                else:
                  messup = input("You mess up while typing on the debugger, and Mr. Cheng regains control of the computer, and start firing code again. You'll have to try to get close again. ")
                  time.sleep(3)
              breakcheng()
            else:
              mcha = input("Too slow. Your mind is destroyed by Mr Cheng's code. YOU ARE TURNED INTO A ROBOT. Press ENTER to try again. ")
              os.system('clear')
              chengp2()
          chengp2()  
        else:
          m = input("Too slow. Your mind is destroyed by Mr Cheng's code. YOU ARE TURNED INTO A ROBOT. Press ENTER to try again. ")
          os.system('clear')
          chengno()
      chengno()
      #ch1 = 1
    else:
      os.system('clear')
      print("That's not a choice. Try again.")
      time.sleep(2)
      os.system('clear')
      join()
  join()    
    
def checkpoint5():
  os.system('clear')
  print("-> Austin pulls out a laptop and starts typing rapidly. What's happened to Austin? ")
  time.sleep(4)
  print("He begins to twitch slightly and then looks you right in the eye.")
  time.sleep(3.6)
  print("'AUSTIN': It's no use resisting. This is our fate, for humanity to fall to technology. It seems we of 9-3 are the pioneers...of something greater. Don't resist. Come with us...")
  time.sleep(7)
  print("-> Austin fires blocks of code at you through his computer. You must avoid them or it will be over. ")
  time.sleep(4.5)
  os.system('clear')
  def checkpoint5b():
    print("-> You pull out the debugger. When Austin fires a code weapon at you, you must unscramble it and enter it in to the debugger in order to disable it. Got that? You have 10 seconds before Austin starts attacking. ")
    time.sleep(10)
    os.system('clear')
    print("3!")
    time.sleep(1)
    os.system('clear')
    print("2!")
    time.sleep(1)
    os.system('clear')
    print("1!")
    time.sleep(1)
    os.system('clear')
    print("GO!")
    time.sleep(1)
    os.system('clear')
    print("'AUSTIN': Prepare for retribution. ")
    time.sleep(3)
    os.system('clear')
    scram1 = input("stykci bmbo: ")
    os.system('clear')
    scram2 = input("fielarbl: ")
    os.system('clear')
    scram3 = input("lsaaemrbe: ")
    os.system('clear')
    if scram1 == "sticky bomb" and scram2 == "fireball" and scram3 == "laserbeam":
      print("-> You manage to evade all of Austin's deadly attacks using the debugger. He keeps sending more and more at you. ")
      time.sleep(3)
      os.system('clear')
      scram4 = input("gneraed: ")
      os.system('clear')
      print("'AUSTIN': All threats must be terminated immediately. It is futile to oppose us. ")
      time.sleep(4)
      print("YOU: Austin! What's happened to you?! ")
      time.sleep(3)
      print("-> Austin doesn't seem to hear you. He continues attacking you. Pick up the pace, you can't give up here! ")
      time.sleep(2.5)
      scram5 = input("ssmiiel: ")
      os.system('clear')
      scram6 = input("rckoet: ")
      os.system('clear')
      if scram4 == "grenade" and scram5 == "missile" and scram6 == "rocket":
        print("-> You have successfully dodged all of Austin's attacks. You run up to Austin and prepare the debugger, but he retreats, almost like being pulled by strings. ")
        time.sleep(3)
        os.system('clear')
        print("-> Austin!!!! Come back!! It's too late. Austin is gone. In his place...is the mastermind himself. ")
        time.sleep(4)
        import page12
        time.sleep(2)
        os.system('clear')
        print("M")
        time.sleep(0.5)
        os.system('clear')
        print("MR")
        time.sleep(0.5)
        os.system('clear')
        print("MR ")
        time.sleep(0.5)
        os.system('clear')
        print("MR C")
        time.sleep(0.5)
        os.system('clear')
        print("MR CH")
        time.sleep(0.5)
        os.system('clear')
        print("MR CHE")
        time.sleep(0.5)
        os.system('clear')
        print("MR CHEN")
        time.sleep(0.5)
        os.system('clear')
        print("MR CHENG")
        time.sleep(5)
        os.system('clear')
        checkpoint6()
    else:
      print("You finally fall to Austin's code attacks. The last thing you see is your beloved intern's face staring at you without expression, and a man behind him as well. It fades to black.")
      time.sleep(6)
      os.system('clear')
      ag = input("YOU DIE. Press ENTER to try again: ")
      time.sleep(.6)
      os.system('clear')
      checkpoint5b()
  checkpoint5b()
print("All characters in this adventure are completely fictional despite being based on real-life characters. This story is complete fiction as well. ")
time.sleep(4)
os.system('clear')
begin = input("Hi! Hit ENTER to begin your adventure!")
os.system('clear')
user = input("Welcome to the Brick Prison.\nWhat is your name? ")
userL = user.lower()
#if we want to skip to a certain line in the code
if 'cheng' in userL or 'mannix' in userL:
  print("Hello, " + str(user) + ", nice to meet you!")
  time.sleep(1.5)
  print("AUSTIN: I'm Austin, your intern, and I'll be guiding you through your mission!") 
  time.sleep(1.5)
  print("Wait...MR CHENG??? Haha, fancy meeting you here...I'm telling you, this project is insanely good, packed with lots of fun and adventure! Chris and Deji spent a lot of time on it. Anyways, hope you enjoy it. Play til the end for a huge surprise! Trust me you'll want to stay for this one. ")
  time.sleep(3.2)
#skip to whichever line
elif user == "Deji" or user == "Chris":
  import page2
elif user == "8":
  import page8
elif user == "3":
  import page3
elif user == "7":
  import page7
elif user == "5":
  import page5
elif user == "12":
  import page12
elif user == "check1":
  checkpoint1()
elif user == "check2":
  checkpoint2()
elif user == "check3":
  checkpoint3()
elif user == "check4":
  checkpoint4()
elif user == "emmitthandball":
  handball()
elif user == "3b":
  checkpoint3b()
elif user == "check5":
  checkpoint5()
elif user == "tennis":
  tennis()
elif user == "check6":
  checkpoint6()
#code begins
else:
  print("Hello, " + str(user) + ", nice to meet you!")
  time.sleep(1.5)
  print("AUSTIN: I'm Austin, your intern, and I'll be guiding you through your mission!")
  time.sleep(3.2)
print("Speaking of your mission, our objective is to infiltrate Hunter College High School.")
time.sleep(3)
print("Wow! Even the name sounds evil...")
time.sleep(1.4)
print("Anyways lets get straight into it.")
time.sleep(1.7)
print("We might come across enemies on our way, so I'm gonna need you to do something...")
time.sleep(3)
print("I have a little surprise for you, but first I gotta see if you're willing to help me out.")
#Trivia #0 (Tutorial) 
time.sleep(4.5)
print("Why don't we try it out? Here's some practice and then I'll give it to you. Ready?")
time.sleep(2.5)
os.system('clear')
starttrivia0 = input("Press any key to START BATTLE")
os.system('clear')
import page1
'''
from threading import Timer
timeout = 10
limit = Timer(timeout, print, ['AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds '])
limit.start()
triv0 = input("AUSTIN: What is the first letter of the alphabet? \nYou must answer in less than 10 seconds.")
answer = input(triv0)
limit.cancel() 
'''
start = time.time()
triv0 = input("AUSTIN: What is the first letter of the alphabet? \nYou must answer in less than 10 seconds.")
end = time.time()
tiv0 = triv0.lower()
if end - start > 10:
  print("AUSTIN: Sorry, you took too long, next time, try to respond in under 10 seconds")
  time.sleep(2.5)
  import page4
  time.sleep(1.5)
  os.system('clear')
  import page4
if triv0 == 'a':
  attack()
  print("AUSTIN: Wow, you're a natural! If that were an enemy they'd be toast! That was easy!")
  time.sleep(4)
  print("All right, get ready to enter. Remember pretend like you are a normal student and DON'T TALK TO ANYONE.")
  time.sleep(4)
  ok = input("Okay? Click ENTER to proceed.")
  print("All right.")
  time.sleep(0.8)
  os.system('clear')
  import page7 
  os.system('clear')
  print("Entering in 5")
  time.sleep(1)
  os.system('clear')
  print("Entering in 4")
  time.sleep(1)
  os.system('clear')
  print("Entering in 3")
  time.sleep(1)
  os.system('clear')
  print("Entering in 2")
  time.sleep(1)
  os.system('clear')
  print("Entering in 1")
  time.sleep(0.5)
  os.system('clear')
  print("Entering.")
  time.sleep(0.5)
  os.system('clear')
  print("Entering..")
  time.sleep(0.5)
  os.system('clear')
  print("Entering...")
  time.sleep(0.5)
  os.system('clear')
  print("Entering..")
  time.sleep(0.5)
  os.system('clear')
  print("Entering.")
  time.sleep(0.5)
  os.system('clear')
  print("Entering..")
  time.sleep(0.5)
  os.system('clear')
  print("Entering...")
  time.sleep(0.5)
  os.system('clear')
  print("Entering..")
  time.sleep(0.5)
  os.system('clear')
  print("You have SUCCESSFULLY entered HCHS")
  time.sleep(1)
  print("AUSTIN: Well, we're here. Let me give you the scoop.")
  time.sleep(2)
  print("I know you just got back from sick leave, but so far you haven't seen many of your classmates, have you? ")
  time.sleep(4)
  print("Someone has programmed all of your classmates to do their bidding. I wonder who it could be? Must be some unknown mastermind pulling the strings.")
  time.sleep(6)
  os.system('clear')
  print("AUSTIN: These robots are very strong and loyal to the programmer. They act like themselves around other robots, but when they see you, the only one not yet a robot...") 
  time.sleep(4)
  print("They will use their superpowers to knock you unconscious, then bring you to the programmer to become the final 9-3 robot." )
  time.sleep(3)
  print("Sounds scary, right? I wonder why this is happening. Whatever the reason, we've got to stop it and save everyone! ")
  time.sleep(5)
  os.system('clear')
  print("These robots are tough. However, if you can render them incapable by one method or another, and then you use this sweet gadget I crafted, they'll be back to normal! Isn't that great?")
  time.sleep(5.5)
  print("You got that?")
  time.sleep(2)
  os.system('clear')
  print("Good. Let's get started. Let me get the debugger I made. Oh, there's one of them right there! What is that?")
  time.sleep(4.5)
  print("Wait...isn't that a wild Sami? I've never seen one in person before.")
  time.sleep(4)
  print("C'MON", str(user.upper()), "YOU GOT THIS!")
  samibattle = input("Press any key to START BATTLE")
  import page1
  checkpoint1() 
  ("AUSTIN: Phew, that was a close call. Let's keep going!")
  time.sleep(2)
  print("-> You walk around the 4th floor hallways, trying to find the source of the code.")
  time.sleep(4)
  print("You hear whirring noises coming from somewhere nearby...")
  time.sleep(3)
  os.system('clear')
  investigatenoise = input("Press ENTER to investigate sounds")
  os.system('clear')
  time.sleep(1)
  print("-> The noises are coming from room 444. How strange! ")
  time.sleep(3)
  os.system('clear')
  print("-> Before you can investigate more, you hear footsteps coming from the other side of the hallway.")
  time.sleep(4)
  print("AUSTIN: Someone's coming! Who is it?!")
  time.sleep(3)
  os.system('clear')
  print("EMMITT: Hello, " + str(user) + ".")
  time.sleep(3)
  os.system('clear')
  checkpoint2()
  os.system('clear')
  print("AUSTIN: Glad we got that over with...let's head to the basement.")
  time.sleep(5)
  basement = input("Press ENTER to go to the basement: ")
  os.system('clear')
  time.sleep(1)
  import page7
  os.system('clear')
  time.sleep(2)
  print("-> You come across two hallways.")
  time.sleep(3)
  print("AUSTIN: The left goes to the bathroom, and the right goes towards the gym. You hear the sound of a basketball bouncing from the right, and splashing sounds from the left. ")
  time.sleep(4)
  os.system('clear')
  checkpoint3()
  print("AUSTIN: Phew, we narrowly escaped again. Let's go to the courtyard, then go up the floors. ")
  time.sleep(4)
  os.system('clear')
  courtyard = input("Press ENTER to go to the courtyard: ")
  os.system('clear')
  time.sleep(2)
  import page7
  os.system('clear')
  time.sleep(2)
  checkpoint4()
  print("AUSTIN: Wow, we've really saved a ton of classmates! I think the only thing left to do is to go back up to that strange room on the 4th floor! ")
  fourthfloor = input("Press ENTER to head to the 4th floor: ")
  os.system('clear')
  time.sleep(1)
  import page7
  os.system('clear')
  print("AUSTIN: Ok, here we are. Room 444...I can tell something very sinister lies behind this door. You hear all that humming? Must be some very powerful computers in there. ")
  time.sleep(7)
  os.system('clear')
  print("AUSTIN: Are you ready to face the mastermind? Let's go! ")
  time.sleep(2)
  os.system('clear')
  r444 = input("Press ENTER to go into room 444: ")
  os.system('clear')
  import page7
  time.sleep(5)
  print("-> Everything goes dark in an instant. Everything is quiet except for the humming of dozens of computers. ")
  time.sleep(5)
  os.system('clear')
  print("YOU: Where is Austin? ")
  time.sleep(5)
  os.system('clear')
  print("-> A cold voice speaks in the darkness. ")
  time.sleep(4)
  os.system('clear')
  print("???: Hi, ")
  time.sleep(0.5)
  os.system('clear')
  print("???: Hi," + user + ".")
  time.sleep(1.2)
  print("I've been waiting for you. ")
  time.sleep(2)
  os.system('clear')
  print("-> A shadowy figure hunched on the ground stands up. ")
  time.sleep(3)
  print("YOU: Austin?? ")
  time.sleep(2)
  print("'AUSTIN': What do we have here, an intruder. Say goodbye to your consciousness. ")
  time.sleep(3)
  os.system('clear')
  import page1
  time.sleep(1)
  os.system('clear')
  print("A")
  time.sleep(0.5)
  os.system('clear')
  print("AU")
  time.sleep(0.5)
  os.system('clear')
  print("AUS")
  time.sleep(0.5)
  os.system('clear')
  print("AUST")
  time.sleep(0.5)
  os.system('clear')
  print("AUSTI")
  time.sleep(0.5)
  os.system('clear')
  print("AUSTIN")
  time.sleep(5)
  os.system('clear')
  chek = input("Press ENTER to start battle.")
  checkpoint5()
  os.system('clear')
  print("Good Game!")
  time.sleep(5)
  print("Why are you still here go do something.")
  time.sleep(5)
  print("Try the code again with a different set of outcomes or something.")
  time.sleep(4)
  os.system('clear')
else:
  print("AUSTIN: I really don't know what to tell you, you messed up pretty bad there...")
  time.sleep(2)
  print("Maybe you're not the one for the job. Sorry to bother you, I'll see you next computer science class")
  


#Write the main part of your program here. Use of the other pages is optional.

#import page1  # uncomment if you're using page1
#import page2  # uncomment if you're using page2
#import page3  # uncomment if you're using page3
#import page4  # uncomment if you're using page4