#Use of this page is optional. If you use code here, make sure either import page3 or from page3 import * appear on your main.py page.
import time
import os
def attack():
  print("           ")
  time.sleep(1)
  os.system('clear')
  print(">           ")
  time.sleep(0.1)
  os.system('clear')
  print("=>           ")
  time.sleep(0.1)
  os.system('clear')
  print("==>          ")
  time.sleep(0.1)
  os.system('clear')
  print("===>         ")
  time.sleep(0.1)
  os.system('clear')
  print("-===>        ")
  time.sleep(0.1)
  os.system('clear')
  print(" -===>       ")
  time.sleep(0.1)
  os.system('clear')
  print("  -===>      ")
  time.sleep(0.1)
  os.system('clear')
  print("   -===>     ")
  time.sleep(0.1)
  os.system('clear')
  print("    -===>    ")
  time.sleep(0.1)
  os.system('clear')
  print("     -===>   ")
  time.sleep(0.1)
  os.system('clear')
  print("      -===>  ")
  time.sleep(0.1)
  os.system('clear')
  print("       -===> ")
  time.sleep(0.1)
  os.system('clear')
  print("        -===>")
  time.sleep(0.1)
  os.system('clear')
  print("         -==*")
  time.sleep(0.1)
  os.system('clear')
  print("          -=*")
  time.sleep(0.1)
  os.system('clear')
  print("            B")
  time.sleep(0.1)
  os.system('clear')
  print("           BO")
  time.sleep(0.1)
  os.system('clear')
  print("          BOO")
  time.sleep(0.1)
  os.system('clear')
  print("         BOOOO")
  time.sleep(0.1)
  os.system('clear')
  print("        BOOOOM")
  time.sleep(0.1)
  os.system('clear')
  print("       BOOOOM ")
  time.sleep(0.1)
  os.system('clear')
  print("      BOOOOM  ")
  time.sleep(0.1)
  os.system('clear')
  print("     BOOOOM   ")
  time.sleep(0.1)
  os.system('clear')
  print("    BOOOOM    ")
  time.sleep(0.1)
  os.system('clear')
  print("   BOOOOM     ")
  time.sleep(0.1)
  os.system('clear')
  print("  BOOOOM      ")
  time.sleep(0.1)
  os.system('clear')
  print(" BOOOOM       ")
  time.sleep(0.1)
  os.system('clear')
  print("BOOOOM        ")
  time.sleep(0.1)
  os.system('clear')
  print("OOOOM         ")
  time.sleep(0.1)
  os.system('clear')
  print("OOOM          ")
  time.sleep(0.1)
  os.system('clear')
  print("OOM           ")
  time.sleep(0.1)
  os.system('clear')
  print("OM            ")
  time.sleep(0.1)
  os.system('clear')
  print("M             ")
  time.sleep(0.1)
  os.system('clear')
  print("              ")
  time.sleep(0.1)
  os.system('clear')
attack()