import time
import os
print("   _ _")
time.sleep(0.1)
print(" / o o \\")
time.sleep(0.1)
print("|   ^   |")
time.sleep(0.1)
print(" \ _ _ /")
time.sleep(0.1)
print("   /|\\")
time.sleep(0.1)
print("  / | \\")
time.sleep(0.1)
print(" /  |  \\")
time.sleep(0.1)
print("    |") 
time.sleep(0.1)
print("   / \\")
time.sleep(0.1)
print(" _/   \\_")
time.sleep(1)
os.system('clear')