#Use of this page is optional. If you use code here, make sure either import page1 or from page1 import * appear on your main.py page.

import time
import os

print("           ")
time.sleep(0.5)
os.system('clear')
print("|           |")
time.sleep(0.1)
os.system('clear')
print("||         ||")
time.sleep(0.1)
os.system('clear')
print("|||       |||")
time.sleep(0.1)
os.system('clear')
print("||||     ||||")
time.sleep(0.1)
os.system('clear')
print("|||||   |||||")
time.sleep(0.1)
os.system('clear')
print("|||||| ||||||")
time.sleep(0.1)
os.system('clear')
print("|||||||||||||")
time.sleep(0.1)
os.system('clear')
print("|||||| B|||||")
time.sleep(0.1)
os.system('clear')
print("|||||l Ba|||||")
time.sleep(0.1)
os.system('clear')
print("||||al Bat||||")
time.sleep(0.1)
os.system('clear')
print("|||nal Batt|||")
time.sleep(0.1)
os.system('clear')
print("||inal Battl||")
time.sleep(0.1)
os.system('clear')
print("|Final Battle|")
time.sleep(2)
os.system('clear')